### PR TITLE
Agent&GraphQL refactor -> 0.1.0

### PR DESCRIPTION
**Pull request by jdeepee**
```
npm run build
npm run buldSchema
```
builds the GraphQL schema from the TypeScript types...

### CODE REVIEW

**Review by lucksus — COMMENTED** [review]
I think we should base this on the other refactor branches - or complete/merge those first as there are quite some changes which will conflict with this.

**Comment by lucksus** [comment]
Regarding the file/directory structure:
I would suggest having a separate directory for the *Service interfaces (`SignatureService` and `AgentService`) - and maybe even a sub-directory below `language` since objects implementing those interfaces are used in the `LanguageContext`, i.e. injected into language implementations by the run-time.

**Comment by lucksus** [comment]
And:
I would like to see the compiled JS code be put into a separate `lib` directory so we can have clean `src` with only the TypeScript sources.

**Comment by jdeepee** [comment]
Made most of the changes outlines here, just confused about the sentence: "and maybe even a sub-directory below language since objects implementing those interfaces are used in the LanguageContext, i.e. injected into language implementations by the run-time." in above reply. 

Probably best to add the interfaces in a co-working sessions since I guess we will do some refactoring there

**Review by lucksus — APPROVED** [review]

**Pull request merged**
